---
- hosts: all
  become: true
  pre_tasks:
    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - apt
    - firewall
    - ssh
- hosts: core
  become: true
  roles:
    - role: traefik
      vars:
        traefik_binary_url: https://github.com/traefik/traefik/releases/download/v2.9.1/traefik_v2.9.1_linux_386.tar.gz
        # TODO: replace with real values
        service:
          name: change-me
          targets:
            - http://localhost:8001
            - http://localhost:8002
            - http://localhost:8003
          host: trailhead.vengal.dev
        dashboard:
          host: traefik.vengal.dev
          authorized_users:
            - "admin:$2y$10$iavjUW.TnmtFi/78QBvDneW0Mx9UrOU6Pm3ZsB9YOvdZZ3M/KceSS"
