---
- name: Create traefik systemd unit
  template:
    src: "traefik.service.j2"
    dest: "/etc/systemd/system/traefik.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart traefik

- name: Ensure expected dirs exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/usr/bin"
    - "/etc"

- name: Copy traefik config file
  template:
    src: "traefik.toml.j2"
    dest: "/etc/traefik.toml"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart traefik

- name: Register traefik bin
  stat:
    path: "/usr/bin/traefik"
  register: traefik_bin

- name: Download traefik binary
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    keep_newer: yes
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "/usr/bin"
  when: traefik_bin.stat.exists == False

- name: Ensure traefik service is running
  systemd:
    name: traefik
    state: started
    enabled: yes
    daemon_reload: yes
